name: Python application

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Install additional dependencies
        run: |
          pip install groq requests

      - name: Run Lint and Tests
        id: lint_test
        run: |
          cd backend
          # Run linting and capture output
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 2>&1 | tee ../error_logs.txt
          # Run tests and append output to error_logs.txt
          python -m unittest discover tests 2>&1 | tee -a ../error_logs.txt

      - name: Notify on Failure
        if: failure()
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          python notify.py error_logs.txt ${AUTHOR}

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Render
        env:
          RENDER_WEBHOOK_URL: ${{ secrets.RENDER_WEBHOOK_URL }}
        run: |
          curl -X POST $RENDER_WEBHOOK_URL

      - name: Notify on failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        run: |
          # Prepare the message

          MESSAGE=$(cat <<EOF
          ⚠️ *Render Deploy Failed* ⚠️
          *Author:* ${AUTHOR_NAME}
          EOF
          )

          # Send the message via Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d parse_mode="Markdown" \
            --data-urlencode text="$MESSAGE"


