name: Vite App CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: |
          cd frontend
          npm ci

      - name: Install Python and dependencies
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - run: |
          pip install groq requests

      - name: Build Vite App
        id: build_app
        run: |
          cd frontend
          npm run build 2>&1 | tee ../error_logs.txt

      - name: Notify on Failure
        if: failure()
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AUTHOR: ${{ github.event.head_commit.author.name }}
        run: |
          python notify.py error_logs.txt ${AUTHOR}

  deploy:
    needs: build
    if: success()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Vercel
        env:
          VERCEL_WEBHOOK_URL: ${{ secrets.VERCEL_WEBHOOK_URL }}
        run: |
          curl -X POST $VERCEL_WEBHOOK_URL

     
      - name: Notify on failure
        if: failure()
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          AUTHOR_NAME: ${{ github.event.head_commit.author.name }}
        run: |
          # Prepare the message

          MESSAGE=$(cat <<EOF
          ⚠️ *Vercel Deploy Failed* ⚠️
          *Author:* ${AUTHOR_NAME}
          EOF
          )

          # Send the message via Telegram
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d parse_mode="Markdown" \
            --data-urlencode text="$MESSAGE"


